FROM nvcr.io/nvidia/deepstream-l4t:5.0-20.07-base

# Install Dependencies
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
    build-essential \
    make \
    cmake \
    curl \
    git \
    g++ \
    gcc \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgtk-3-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libgirepository1.0-dev \
    libmysqlclient-dev \
    zlib1g-dev \
    python-pip \
    python3-pip \
    python3-dev \
    tzdata \
    uvccapture \
    libgstreamer1.0-0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-doc \
    gstreamer1.0-tools \
    python-gst-1.0 \
    python3-gst-1.0 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

# for japanese
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"

ENV PATH=/usr/local/cuda-10.0/bin:$PATH \
    LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH

RUN git clone https://github.com/FFmpeg/nv-codec-headers -b n10.0.26.0 && \
    cd ./nv-codec-headers && \
    make -j && \
    make install -j && \
    cd .. && rm -rf nv-codec-headers

RUN git clone https://git.ffmpeg.org/ffmpeg.git && \
    cd ./ffmpeg && \
    git checkout f95dac666caea27c && \
    ./configure \
    --enable-nonfree \
    --enable-pic \
    --enable-shared \
    --enable-nvenc \
    --enable-cuda \
    --enable-cuvid \
    --extra-cflags=-I/usr/local/cuda/include \
    --extra-cflags=-I/usr/local/include \
    --extra-ldflags=-L/usr/local/cuda/lib64 && \
    make -j && make install && \
    cd .. && rm -rf ffmpeg

# required in opencv
RUN python3 -m pip install numpy==1.17.4 && \
    python -m pip install numpy==1.16.6

RUN mkdir -p /tmp/python-cv2
WORKDIR /tmp/python-cv2

# Install OPENCV 4.1.2 With CUDA
ARG CUDA_COMPUTE_CAPABILITY
RUN git clone https://github.com/opencv/opencv.git -b 4.1.2 \
    && git clone https://github.com/opencv/opencv_contrib -b 4.1.2 \
    && mkdir /tmp/python-cv2/opencv/build

RUN cd /tmp/python-cv2/opencv/build \
    && cmake \
       -D CMAKE_BUILD_TYPE=RELEASE \
       -D CMAKE_INSTALL_PREFIX=/usr/local \
       -D WITH_CUDA=ON \
       -D CUDA_ARCH_BIN=${CUDA_COMPUTE_CAPABILITY} \
       -D CUDA_ARCH_PTX="" \
       -D WITH_CUBLAS=ON \
       -D ENABLE_FAST_MATH=ON \
       -D CUDA_FAST_MATH=ON \
       -D ENABLE_NEON=ON \
       -D WITH_LIBV4L=ON \
       -D BUILD_TESTS=OFF \
       -D BUILD_PERF_TESTS=OFF \
       -D BUILD_EXAMPLES=OFF \
       -D WITH_QT=OFF \
       -D WITH_OPENGL=ON \
       -D WITH_FFMPEG=ON \
       -D BUILD_opencv_java=OFF \
       -D BUILD_opencv_python=OFF \
       -D BUILD_opencv_python3=ON \
       -D PYTHON_DEFAULT_EXECUTABLE=/usr/bin/python3 \
       -D BUILD_opencv_xfeatures2d=OFF \
       -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
       -D BUILD_opencv_cudaoptflow=OFF .. \
    && make -j"$(nproc)" \
    && make install \
    && rm -rf /tmp/python-cv2/opencv /tmp/python-cv2/opencv_contrib \
    && ldconfig

# Dependencies about mysqlclient
RUN git clone https://github.com/edenhill/librdkafka && \
    cd librdkafka && \
    ./configure --prefix=/usr && \
    make && \
    make install && \
    cd ../ && \
    rm -rf librdkafka

ADD dist .
ENV GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS 8
RUN python3 -m pip install ./aion-*.tar.gz

CMD ["/bin/bash"]
