FROM nvcr.io/nvidia/l4t-base:r32.3.1

# Install Dependencies
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    g++ \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgtk-3-dev \
    libssl-dev \
    libgtk-3-dev \
    libcurl4-openssl-dev \
    python-pip \
    python3-pip \
    python3-dev \
    tzdata \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

# for japanese
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"

RUN export GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=8 && \
    python3 -m pip install grpcio

ENV  PATH /usr/local/cuda-10.2/bin:${PATH}
ENV  LD_LIBRARY_PATH /usr/local/cuda-10.2/lib64:${LD_LIBRARY_PATH}

RUN pip3 install cython attrs==19.1.0 cupy==7.3
ADD dist .
ENV GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS 8
RUN --mount=type=cache,target=/root/.cache/pip python3 -m pip install ./aion-*.tar.gz

CMD ["/bin/bash"]
